USE DESKTOP_ADV
--SELECT DISTINCT submission_date FROM Submissions

SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-01' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-01' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-01' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-01' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-01' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-01')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-01' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-01')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-01'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-02' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-02' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-02' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-02' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-02' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-02')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-02' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-02')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-02'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-03' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-03' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-03' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-03' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-03' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-03')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-03' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-03')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-03'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-04' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-04' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-04' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-04' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-04' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-04')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-04' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-04')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-04'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-05' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-05' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-05' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-05' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-05' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-05')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-05' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-05')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-05'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-06' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-06' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-06' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-06' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-06' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-06')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-06' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-06')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-06'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-07' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-07' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-07' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-07' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-07' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-07')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-07' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-07')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-07'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-08' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-08' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-08' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-08' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-08' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-08')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-08' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-08')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-08'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-09' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-09' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-09' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-09' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-09' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-09')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-09' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-09')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-09'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-10' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-10' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-10' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-10' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-10' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-10')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-10' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-10')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-10'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-11' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-11' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-11' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-11' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-11' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-11')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-11' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-11')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-11'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-12' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-12' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-12' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-12' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-12' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-12')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-12' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-12')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-12'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-13' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-13' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-13' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-13' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-13' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-13')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-13' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-13')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-13'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-14' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-14' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-14' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-14' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-14' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-14')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-14' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-14')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-14'
UNION
SELECT DISTINCT Submissions.submission_date, tblFive.Count_Reg_Hacker, tblxFive.hacker_id,  tblxFive.name FROM (Submissions LEFT JOIN (SELECT tblFour.submission_date, COUNT(tblFour.hacker_count) AS Count_Reg_Hacker  FROM 
	(SELECT N'2016-03-15' AS submission_date, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
		(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-15' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id HAVING ((COUNT(tblOne.hacker_id) IN (SELECT MAX(tblThree.Max_Hacker_Count) FROM 
			(SELECT tblTwo.hacker_id, MAX(tblTwo.hacker_count) AS Max_Hacker_Count FROM 
				(SELECT N'2016-03-15' AS submission_date, tblOne.hacker_id, COUNT(tblOne.hacker_id) AS hacker_count  FROM 
					(SELECT DISTINCT submission_date, hacker_id FROM Submissions WHERE Submissions.submission_date <= N'2016-03-15' GROUP BY submission_date, hacker_id) AS tblOne GROUP BY tblOne.hacker_id) AS tblTwo GROUP BY tblTwo.hacker_id) AS tblThree)))) AS tblFour GROUP BY tblFour.submission_date) AS tblFive ON Submissions.submission_date = tblFive.submission_date) LEFT JOIN 
					( SELECT tblxFour.submission_date, tblxFour.hacker_id, Hackers.name FROM (SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id) AS hacker_id FROM 
	(SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM 
		(SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM 
			(SELECT DISTINCT N'2016-03-15' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-15')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN 
				(SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-15' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-15')) AS tblxOne)))) AS tblxThree GROUP BY tblxThree.submission_date) AS tblxFour INNER JOIN Hackers ON tblxFour.hacker_id = Hackers.hacker_id  ) AS tblxFive ON Submissions.submission_date = tblxFive.submission_date WHERE Submissions.submission_date = N'2016-03-15'
