DECLARE @sub_date nvarchar(20)
DECLARE @SSQL nvarchar(MAX)
SET @sub_date = N'2016-03-02'

--SELECT DISTINCT Submissions.submission_date FROM Submissions GROUP BY Submissions.submission_date

SET @SSQL = 'SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id), Hackers.name FROM (SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM (SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM (SELECT DISTINCT ' + 'N''' + @sub_date + '''' + ' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = ' + 'N''' + @sub_date + '''' + ')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN (SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT ' + 'N''' + @sub_date + '''' + ' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = ' + 'N''' + @sub_date + '''' + ')) AS tblxOne)))) AS tblxThree LEFT JOIN Hackers ON tblxThree.hacker_id = Hackers.hacker_id GROUP BY tblxThree.submission_date, Hackers.name'

--SET @SSQL = 'SELECT DISTINCT Submissions.submission_date FROM Submissions GROUP BY Submissions.submission_date'
PRINT (@SSQL)

SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id), Hackers.name FROM (SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM (SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-01' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-01')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN (SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-01' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-01')) AS tblxOne)))) AS tblxThree LEFT JOIN Hackers ON tblxThree.hacker_id = Hackers.hacker_id GROUP BY tblxThree.submission_date, Hackers.name
UNION SELECT tblxThree.submission_date, MIN(tblxThree.hacker_id), Hackers.name FROM (SELECT tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions FROM (SELECT tblxOne.submission_date, tblxOne.hacker_id, (tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-02' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-02')) AS tblxOne GROUP BY tblxOne.submission_date, tblxOne.hacker_id, tblxOne.hacker_submissions) AS tblxTwo GROUP BY tblxTwo.submission_date, tblxTwo.hacker_id, tblxTwo.hacker_submissions  HAVING (((tblxTwo.hacker_submissions) IN (SELECT MAX(tblxOne.hacker_submissions) FROM (SELECT DISTINCT N'2016-03-02' as submission_date, hacker_id, COUNT(hacker_id) AS hacker_submissions FROM Submissions GROUP BY submission_date, hacker_id HAVING (Submissions.submission_date = N'2016-03-02')) AS tblxOne)))) AS tblxThree LEFT JOIN Hackers ON tblxThree.hacker_id = Hackers.hacker_id GROUP BY tblxThree.submission_date, Hackers.name
