
/*(SELECT P AS NODE FROM BST GROUP BY P UNION SELECT N FROM BST GROUP BY N);

SELECT P AS NODE FROM BST WHERE P IS NOT NULL GROUP BY P;

SELECT N, P FROM BST WHERE (N IN (SELECT P AS NODE FROM BST GROUP BY P UNION SELECT N FROM BST GROUP BY N)) AND (P IN (SELECT P AS NODE FROM BST GROUP BY P UNION SELECT N FROM BST GROUP BY N)); */

SELECT N, 'Root' AS NodeType FROM BST WHERE (P IS NULL) UNION SELECT N, 'Inner' AS NodeType FROM BST WHERE (N IN (SELECT P FROM BST WHERE P IS NOT NULL GROUP BY P)) AND P IS NOT NULL UNION SELECT N, 'Leaf' AS NodeType FROM BST WHERE (N NOT IN(SELECT P FROM BST WHERE P IS NOT NULL GROUP BY P)) AND P IS NOT NULL;